# Generated by Django 5.2.5 on 2026-03-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Seller', 'Seller'), ('Buyer', 'Buyer'), ('Admin', 'Admin')], max_length=10, null=True),
        ),
    ]
