# Generated by Django 5.2.5 on 2025-08-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Seller', 'Seller'), ('Buyer', 'Buyer')], max_length=10, null=True),
        ),
    ]
