# Generated by Django 5.2.5 on 2025-09-04 05:56

import django.core.validators
import django.db.models.deletion
import services.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_category_servicereview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicereview',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/', validators=[services.validators.validate_file_size])),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service')),
            ],
        ),
    ]
