# Generated by Django 5.2.5 on 2025-09-04 09:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_servicereview_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
